### ISSUE TITLE
In-depth review

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/PhD-Thesis#2]
@mielvds @RubenVerborgh Could you have a look at the current state of the document?

Everything should be in there already, ~~except for a preface and dutch summary, which I will write afterwards.
I also still have to tweak styling a bit, especially print-view, so don't look at that too much :-)~~

One question regarding references: All references are currently collected in one place at the end. Is this ok? Or would it be better to separate them per chapter? (I'm not doing this yet due to technical limitations with ScholarMarkdown, but should be implementable)

**Comment by RubenVerborgh** [comment]
Refs ok; will look at the rest.

**Comment by rubensworks** [comment]
Preface, dutch summary and styling (screen+print) are now also ready. So everything should be in a submission-ready state.

**Comment by RubenVerborgh** [comment]
My review in https://github.com/rubensworks/PhD-Thesis/tree/review/rv.

Happy overall, but the conclusion is missing a critical description of the limitations of the work. Be critical about your work, explain what you wanted to learn but didn't, what you hoped to find but didn't, anything that scopes this work in a realistic way. Lessons learned also, if possible. (I like the conclusions about the individual chapters.)

**Comment by rubensworks** [comment]
Thanks, will have a look at it asap.
